### ISSUE TITLE
Rename repository?

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [pdtpartners/nix-snapshotter#89]
This is a super cool project, and I can't wait to play around with it :)) but I believe that discoverability will suffer due to the poor repository name. May I suggest naming something along the lines of `nix-native-oci-images`

**Comment by adrian-gierakowski** [comment]
nix-oci-snapshotter
or
nix-containerd-snapshotter ??

Although a bit long

**Comment by gytis-ivaskevicius** [comment]
Yeah, I guess the name makes sense. Thanks
